<?php

namespace yiiunit\extensions\graphql;

use yii\web\Controller;

class DefaultController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actions()
    {
        return [
            'index' => [
                'class' => 'yii\graphql\GraphQLAction',
            ]
        ];
    }
}
